### PR TITLE
Fixes a lot of clippy errors (lints) and does reformat the files according to Rust style guides

### PR DESCRIPTION
**Pull request by SirWindfield**
Hey!

I've ran `cargo clippy` on the code and fixed almost all of the issues. They are actually split into separate commits, making it easier for you to take a look at them. Clippy reported a bug [here](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/app_bar.rs#L103). `grid` is a reference and calling `drop` on references is no-op. You need to call it on the real object. Taking a closer look it seems that you `drop` the TileGrid that is stored inside the `GRIDS` Mutex. Isn't it just enough to simply remove the element from the `GRIDS` vector and leave it there? 

Generally speaking, you do not really use `std::mem::drop` in "normal" Rust code. But given that you interact with native using `winapi`, as long as you use their API and do not write custom wrappers, Rust will actually take care of dropping everything. Meaning that you shouldn't ever need to call it by yourself.

Another catch that I didn't fix is the `WORK_MODE` Mutex. A Mutex with a bool value can just be replaced with an `AtomicBool` in almost all cases.

The last commits are so large because I ran `cargo fmt`, a tool that formats your source code automatically. It doesn't change any logic inside the files, so you don't have to worry about bugs or stuff. It's just styling.

Given that the value isn't dropped as you might have thought this might actually be the cause for the lag over time, allocating more and more RAM. I am however not sure here and it might be worth to monitor the program and resource usage. Maybe introduce a debug key stroke that prints the length of the `GRIDS` vector and see if it cleans up properly. 

The code is good for your first project. But it is quite obvious that you didn't have used Rust for along time. Which means, more practice :p

### CODE REVIEW

**Comment by SirWindfield** [comment]
You better just squash the changes if you decide to merge, else the git history will get cluttered a lot. Just call the commit `refactor: fix clippy warnings` or something like that. :)

**Comment by TimUntersberger** [comment]
Thank you!

This was definitely needed!

> Taking a closer look it seems that you drop the TileGrid that is stored inside the GRIDS Mutex. Isn't it just enough to simply remove the element from the GRIDS vector and leave it there?

I don't really want to remove the grid from the vector I just tried to somehow resolve the deadlock that happens when you remove the drop statements. Do you have any general advise for such cases?

> Another catch that I didn't fix is the WORK_MODE Mutex. A Mutex with a bool value can just be replaced with an AtomicBool in almost all cases.

Does this have any significant impact? If not then I will just create an issue with low priority for simplifying the Mutex usage.

**Comment by SirWindfield** [comment]
> Does this have any significant impact? If not then I will just create an issue with low priority for simplifying the Mutex usage.

No, it shouldn't. Clippy even mentioned it as a fix :)



> I don't really want to remove the grid from the vector I just tried to somehow resolve the deadlock that happens when you remove the drop statements. Do you have any general advise for such cases?

What exactly deadlocks in your case? A little bit more insight might be good before I throw out some potential solutions :D

**Comment by TimUntersberger** [comment]
I first lock the GRIDS Mutex [here](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/app_bar.rs#L96) to get the current grid then I call the [change_workspace function](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/app_bar.rs#L105) which also needs to know about the current grid and it locks the Mutex [here](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/main.rs#L118).

**Comment by TimUntersberger** [comment]
Do you also know about a way to put the common functionality 

```rust
let mut grids = GRIDS.lock().unwrap();
let grid = grids
    .iter_mut()
    .find(|g| g.id == id)
    .unwrap();
```

into a function? I tried to refactor this code before, but it looks like there is no way to set the lifetime of the lock?

This is how I would refactor this into a function:

```rust
fn get_grid(id: i32) -> Option<&mut TileGrid> {
    let mut grids = GRIDS.lock().unwrap();

    grids
        .iter_mut()
        .find(|g| g.id == id)
}
```

**Comment by SirWindfield** [comment]
> I first lock the GRIDS Mutex [here](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/app_bar.rs#L96) to get the current grid then I call the [change_workspace function](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/app_bar.rs#L105) which also needs to know about the current grid and it locks the Mutex [here](https://github.com/TimUntersberger/wwm/blob/aa139b8aa50e59619740df76415c86cd373f81c5/src/main.rs#L118).

Gotcha. Quite stupid situation you are in there :) I'd probably just change the `change_workspace` function to take a reference to the `GRIDS` value. That way, it can read the current value.


> into a function? I tried to refactor this code before, but it looks like there is no way to set the lifetime of the lock?

I don't think that this works. You are creating a reference inside the function (by accessing the lock) of the `Vec` and returning an element of it. The value would probably go out of scope after the function returns.

Maybe something simple like this should be fine:

```rust
pub fn change_workspace(id: i32, grids: &mut Vec<TileGrid>) -> Result<(), util::WinApiResultError> {
    // ...
}

// how to call
let mut grids = GRIDS.lock().unwrap();
change_workspace(0, &grids);
```

**Comment by TimUntersberger** [comment]
Thank you!

**Pull request merged**
